# Generated by Django 6.0.7 on 2026-08-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_order_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
